version: 2
jobs:
  build:
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
      XCODE_SCHEME: browse.goodcity
      XCODE_WORKSPACE: browse.goodcity
      GYM_CODE_SIGNING_IDENTITY: "iPhone Distribution: Crossroads Foundation Limited"
      FL_TESTFAIRY_AUTO_UPDATE: "on"
      PILOT_SKIP_SUBMISSION: true
      PILOT_WAIT_PROCESSING_INTERVAL: 60
      ANDROID_HOME: "${HOME}/android-sdk"
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:$HOME/.yarn/bin:$ANDROID_HOME/tools"

  - run:
    name: Pre installations
    command: brew update
    command: brew install homebrew/core/node6-lts
    command: brew install watchman
    command: mkdir -p ${ANDROID_HOME}
    command: if ! $(grep -q "Revision=23.0.1" $ANDROID_HOME/tools/source.properties); then (curl -o ~/android-sdk.zip https://dl.google.com/android/repository/tools_r23.0.1-macosx.zip && unzip -d ${ANDROID_HOME} ~/android-sdk.zip) && (( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --no-ui --all --filter platform-tools,build-tools-23.0.1,android-23,extra-android-m2repository,extra-google-m2repository); fi
    command: if ! (which yarn); then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
    command: yarn install
    command: yarn add --force node-sass
    command: yarn add bower ember-cli@2.12.2 phantomjs-prebuilt cordova
    command: yarn add codeclimate-test-reporter
    command: bundle install
    command: bower install
    command: PATH=$(npm bin):$PATH; azure-filestore download -f goodcity.keystore: pwd: cordova
    command: PATH=$(npm bin):$PATH; azure-filestore download -d google-play -f $GOOGLE_PLAY_KEY_FILE: pwd: fastlane

  -run:
    name: Tests
    command: ember server
    command: sleep 5
    command: COVERAGE=true ember test
    command: codeclimate-test-reporter < 'coverage/lcov.info'
    command: ember build
    command: echo "Killing ember server to free memory for app build" && killall ember

  deployment:
    staging:
      branch: master
      commands:
        - bundle exec cap staging deploy
        - bundle exec rake staging ios app:build
        - bundle exec fastlane ios staging
        - bundle exec rake staging android app:build
        - bundle exec fastlane android staging
        - curl https://api.rollbar.com/api/1/sourcemap/download -F access_token=$ROLLBAR_KEY -F version=$APP_VERSION -F minified_url=https://browse-staging.goodcity.hk/assets/browse.js
    production:
      branch: live
      commands:
        - bundle exec cap production deploy
        - bundle exec rake production android app:build
        - bundle exec rake production ios app:build
        - bundle exec fastlane android beta
        - bundle exec fastlane ios beta
        - curl https://api.rollbar.com/api/1/sourcemap/download -F access_token=$ROLLBAR_KEY -F version=$APP_VERSION -F minified_url=https://browse.goodcity.hk/assets/browse.js
